import type { Product } from "@/types"

export interface Testimonial {
  id: string
  name: string
  role: string
  avatar: string
  content: string
  rating: number
  location: string
}

export interface FlashDeal extends Product {
  soldPercent: number
}

export interface BlogPost {
  id: string
  title: string
  slug: string
  excerpt: string
  emoji: string
  author: string
  date: Date
  readTime: string
  category: string
  comments: number
  likes: number
}

export const sampleProducts: Product[] = [
  {
    id: "fp1",
    name: "Premium Velvet Prayer Mat - Extra Large",
    slug: "premium-velvet-prayer-mat-xl",
    description: "",
    price: 18900,
    discountPrice: 12900,
    currency: "KES",
    images: [],
    categoryId: "1",
    sellerId: "1",
    sku: "PVM-XL",
    stock: 32,
    isActive: true,
    isFeatured: true,
    isFlashSale: false,
    tags: ["prayer-mat", "velvet"],
    averageRating: 4.9,
    reviewCount: 312,
    salesCount: 890,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "fp2",
    name: "Deluxe Quran Set with Rehal & Tasbih",
    slug: "deluxe-quran-set-rehal-tasbih",
    description: "",
    price: 35000,
    discountPrice: 24900,
    currency: "KES",
    images: [],
    categoryId: "2",
    sellerId: "1",
    sku: "DQS-002",
    stock: 18,
    isActive: true,
    isFeatured: true,
    isFlashSale: false,
    tags: ["quran", "set"],
    averageRating: 5.0,
    reviewCount: 445,
    salesCount: 1203,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "fp3",
    name: "Organic Black Seed Oil - 500ml",
    slug: "organic-black-seed-oil-500ml",
    description: "",
    price: 9500,
    discountPrice: 6900,
    currency: "KES",
    images: [],
    categoryId: "11",
    sellerId: "1",
    sku: "BSO-003",
    stock: 64,
    isActive: true,
    isFeatured: true,
    isFlashSale: false,
    tags: ["oil", "black-seed"],
    averageRating: 4.7,
    reviewCount: 198,
    salesCount: 567,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "fp4",
    name: "Embroidered Kaftan Abaya - Gold Trim",
    slug: "embroidered-kaftan-abaya-gold",
    description: "",
    price: 45000,
    discountPrice: 32900,
    currency: "KES",
    images: [],
    categoryId: "5",
    sellerId: "1",
    sku: "EKA-004",
    stock: 12,
    isActive: true,
    isFeatured: true,
    isFlashSale: false,
    tags: ["abaya", "kaftan"],
    averageRating: 4.8,
    reviewCount: 167,
    salesCount: 423,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "fp5",
    name: "Premium Oud Bakhoor Gift Set",
    slug: "premium-oud-bakhoor-gift-set",
    description: "",
    price: 22000,
    discountPrice: 15900,
    currency: "KES",
    images: [],
    categoryId: "11",
    sellerId: "1",
    sku: "OBG-005",
    stock: 27,
    isActive: true,
    isFeatured: true,
    isFlashSale: false,
    tags: ["oud", "bakhoor"],
    averageRating: 4.9,
    reviewCount: 256,
    salesCount: 678,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "fp6",
    name: "Islamic Wall Art - Ayatul Kursi Calligraphy",
    slug: "islamic-wall-art-ayatul-kursi",
    description: "",
    price: 28000,
    discountPrice: 19900,
    currency: "KES",
    images: [],
    categoryId: "15",
    sellerId: "1",
    sku: "IWA-006",
    stock: 21,
    isActive: true,
    isFeatured: true,
    isFlashSale: false,
    tags: ["wall-art", "calligraphy"],
    averageRating: 4.9,
    reviewCount: 289,
    salesCount: 745,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
]

export const productEmojis: Record<string, string> = {
  fp1: "🕌",
  fp2: "📖",
  fp3: "🫒",
  fp4: "👗",
  fp5: "🎁",
  fp6: "🖼️",
}

export const sampleFlashDeals: FlashDeal[] = [
  {
    id: "fd1",
    name: "Premium Velvet Prayer Mat - Large",
    slug: "premium-velvet-prayer-mat-large",
    description: "",
    price: 15000,
    discountPrice: 8900,
    currency: "KES",
    images: [],
    categoryId: "1",
    sellerId: "1",
    sku: "PML-001",
    stock: 45,
    isActive: true,
    isFeatured: false,
    isFlashSale: true,
    tags: ["prayer-mat", "velvet"],
    averageRating: 4.8,
    reviewCount: 234,
    salesCount: 567,
    createdAt: new Date(),
    updatedAt: new Date(),
    soldPercent: 72,
  },
  {
    id: "fd2",
    name: "Luxury Oud Perfume Oil - 12ml",
    slug: "luxury-oud-perfume-oil-12ml",
    description: "",
    price: 25000,
    discountPrice: 12900,
    currency: "KES",
    images: [],
    categoryId: "11",
    sellerId: "1",
    sku: "OPO-002",
    stock: 28,
    isActive: true,
    isFeatured: false,
    isFlashSale: true,
    tags: ["perfume", "oud"],
    averageRating: 4.9,
    reviewCount: 189,
    salesCount: 412,
    createdAt: new Date(),
    updatedAt: new Date(),
    soldPercent: 85,
  },
  {
    id: "fd3",
    name: "Qur'an with English Translation - Leather Bound",
    slug: "quran-english-translation-leather",
    description: "",
    price: 18000,
    discountPrice: 9900,
    currency: "KES",
    images: [],
    categoryId: "2",
    sellerId: "1",
    sku: "QET-003",
    stock: 33,
    isActive: true,
    isFeatured: false,
    isFlashSale: true,
    tags: ["quran", "leather"],
    averageRating: 5.0,
    reviewCount: 312,
    salesCount: 789,
    createdAt: new Date(),
    updatedAt: new Date(),
    soldPercent: 60,
  },
  {
    id: "fd4",
    name: "Premium Silk Hijab - Shayla Style",
    slug: "premium-silk-hijab-shayla",
    description: "",
    price: 8500,
    discountPrice: 4900,
    currency: "KES",
    images: [],
    categoryId: "6",
    sellerId: "1",
    sku: "PSH-004",
    stock: 52,
    isActive: true,
    isFeatured: false,
    isFlashSale: true,
    tags: ["hijab", "silk"],
    averageRating: 4.7,
    reviewCount: 156,
    salesCount: 345,
    createdAt: new Date(),
    updatedAt: new Date(),
    soldPercent: 90,
  },
]

export const flashDealEmojis: Record<string, string> = {
  fd1: "🕌",
  fd2: "🧴",
  fd3: "📖",
  fd4: "🧕",
}

export const trendingProducts: Product[] = [
  {
    id: "tr1",
    name: "Raspberry Perfume - Premium Attar",
    slug: "raspberry-perfume-premium-attar",
    description: "",
    price: 12000,
    discountPrice: 8900,
    currency: "KES",
    images: [],
    categoryId: "11",
    sellerId: "1",
    sku: "RPA-001",
    stock: 38,
    isActive: true,
    isFeatured: false,
    isFlashSale: false,
    tags: ["perfume", "attar"],
    averageRating: 4.9,
    reviewCount: 423,
    salesCount: 1234,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "tr2",
    name: "Complete Prayer Set - Mat, Cap, Tasbih",
    slug: "complete-prayer-set-mat-cap-tasbih",
    description: "",
    price: 22000,
    discountPrice: 15900,
    currency: "KES",
    images: [],
    categoryId: "1",
    sellerId: "1",
    sku: "CPS-002",
    stock: 24,
    isActive: true,
    isFeatured: false,
    isFlashSale: false,
    tags: ["prayer-set"],
    averageRating: 4.8,
    reviewCount: 312,
    salesCount: 987,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "tr3",
    name: "Turkish Cotton Towel Set - 6 Pieces",
    slug: "turkish-cotton-towel-set-6pc",
    description: "",
    price: 18500,
    discountPrice: 12900,
    currency: "KES",
    images: [],
    categoryId: "10",
    sellerId: "1",
    sku: "TTS-003",
    stock: 45,
    isActive: true,
    isFeatured: false,
    isFlashSale: false,
    tags: ["towel", "turkish"],
    averageRating: 4.7,
    reviewCount: 189,
    salesCount: 654,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "tr4",
    name: "Brass Islamic Compass (Qibla Finder)",
    slug: "brass-islamic-compass-qibla-finder",
    description: "",
    price: 6500,
    discountPrice: 4500,
    currency: "KES",
    images: [],
    categoryId: "21",
    sellerId: "1",
    sku: "BIC-004",
    stock: 67,
    isActive: true,
    isFeatured: false,
    isFlashSale: false,
    tags: ["compass", "qibla"],
    averageRating: 4.6,
    reviewCount: 134,
    salesCount: 456,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
]

export const trendingEmojis: Record<string, string> = {
  tr1: "🧴",
  tr2: "🕌",
  tr3: "🧣",
  tr4: "🧭",
}

export const testimonials: Testimonial[] = [
  {
    id: "1",
    name: "Aisha Muhammad",
    role: "Verified Buyer",
    avatar: "",
    content:
      "I purchased the Premium Velvet Prayer Mat and it exceeded my expectations. The quality is exceptional — soft, durable, and beautifully designed. Shipping was fast too. JazakAllah khair!",
    rating: 5,
    location: "Nairobi, Kenya",
  },
  {
    id: "2",
    name: "Fatima Usman",
    role: "Verified Buyer",
    avatar: "",
    content:
      "Amir Islamic Collections is my go-to for all Islamic products. The Luxury Oud Perfume is absolutely divine, long-lasting and authentic. Their customer service is outstanding. Highly recommended!",
    rating: 5,
    location: "Mombasa, Kenya",
  },
  {
    id: "3",
    name: "Zaynab Abdullah",
    role: "Verified Buyer",
    avatar: "",
    content:
      "The Deluxe Quran Set made the perfect Eid gift for my parents. The leather binding is exquisite, and the calligraphy is stunning. Thank you for spreading barakah through your products.",
    rating: 5,
    location: "Kisumu, Kenya",
  },
  {
    id: "4",
    name: "Khadija Hassan",
    role: "Verified Buyer",
    avatar: "",
    content:
      "I bought the complete hijab collection and I'm thoroughly impressed. The fabrics are breathable, colors are vibrant, and the pricing is very fair. Will definitely be ordering again!",
    rating: 4,
    location: "Nakuru, Kenya",
  },
  {
    id: "5",
    name: "Aminat Bello",
    role: "Verified Buyer",
    avatar: "",
    content:
      "Their Ramadan collection is absolutely wonderful! The dates were fresh, the decor items tasteful, and the whole experience felt truly special. May Allah bless this business abundantly.",
    rating: 5,
    location: "Eldoret, Kenya",
  },
]

export const blogPosts: BlogPost[] = [
  {
    id: "1",
    title: "The Beauty of Ramadan: A Guide to Spiritual Preparation",
    slug: "beauty-of-ramadan-guide",
    excerpt:
      "Discover practical tips for spiritual and physical preparation ahead of the blessed month of Ramadan, including recommended products and daily routines.",
    emoji: "🌙",
    author: "Amir Islamic Team",
    date: new Date("2025-02-15"),
    readTime: "5 min read",
    category: "Ramadan",
    comments: 24,
    likes: 156,
  },
  {
    id: "2",
    title: "Choosing the Perfect Prayer Mat: A Complete Guide",
    slug: "choosing-perfect-prayer-mat",
    excerpt:
      "From material to size and design, learn everything you need to know about selecting the perfect prayer mat for your home, travel, or gift-giving.",
    emoji: "🕌",
    author: "Aisha Muhammad",
    date: new Date("2025-01-28"),
    readTime: "4 min read",
    category: "Guides",
    comments: 18,
    likes: 98,
  },
  {
    id: "3",
    title: "Essential Islamic Books Every Muslim Home Should Have",
    slug: "essential-islamic-books",
    excerpt:
      "A curated list of must-have Islamic books covering Quran, Hadith, Fiqh, and spirituality to enrich your knowledge and strengthen your iman.",
    emoji: "📚",
    author: "Fatima Usman",
    date: new Date("2025-01-10"),
    readTime: "6 min read",
    category: "Books",
    comments: 31,
    likes: 212,
  },
]
