services:
  - type: web
    name: amir-islamic-collection
    env: docker
    repo: https://github.com/astromuema12/amir-islamic-collection
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://amir-islamic-collection.onrender.com
      - key: DB_DRIVER
        value: pgsql
      - key: DB_HOST
        value: REPLACE_ME
      - key: DB_PORT
        value: 5432
      - key: DB_NAME
        value: postgres
      - key: DB_USER
        value: postgres
      - key: DB_PASS
        value: REPLACE_ME
      - key: SITE_NAME
        value: "Amir Islamic Collection"
      - key: SITE_EMAIL
        value: info@amirislaminiccollection.com
      - key: SITE_PHONE
        value: +254712345678
      - key: SITE_CURRENCY
        value: KES
      - key: SITE_TAX
        value: 16
